### ISSUE TITLE
gui.py doesn't work correctly

### ISSUE THREAD

**Issue by Nuc1eoN** [KenMacD/wdpassport-utils#3]
When typing in the password to gui.py and clicking decrypt I get:

     Calling external cookpw-script...
     Script calling went wrong, pls check if the path to cookpw.py is correct!

Even though ```cookpw.py``` is in the same folder.
And in the console it says:

     /bin/sh: /password.bin: Not auhorized

**Comment by Nuc1eoN** [comment]
I just tried it with the latest git version and started it using python2:
````
$ python2 gui.py 
Traceback (most recent call last):
  File "/home/nuc/wdpass/wdpassport-utils/cookpw.py", line 25, in <module>
    main(sys.argv[1])
  File "/home/nuc/wdpass/wdpassport-utils/cookpw.py", line 17, in main
    header = header.decode("hex")
AttributeError: 'str' object has no attribute 'decode'
````
Weirdly it's the same issue I've had with the console version when using python3....
